In [1]:
pip list

Package                   Version
------------------------- -----------
absl-py                   2.4.0
anyio                     4.13.0
argon2-cffi               25.1.0
argon2-cffi-bindings      25.1.0
arrow                     1.4.0
asttokens                 3.0.1
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.14.3
bleach                    6.3.0
certifi                   2026.2.25
cffi                      2.0.0
charset-normalizer        3.4.7
click                     8.4.0
colorama                  0.4.6
comm                      0.2.3
comtypes                  1.4.16
contourpy                 1.3.3
cycler                    0.12.1
debugpy                   1.8.20
decorator                 5.2.1
defusedxml                0.7.1
et_xmlfile                2.0.0
executing                 2.2.1
fastjsonschema            2.21.2
filelock                  3.28.0
flatbuffers               25.12.19
fonttools                 4.62.1
fqdn                      1.5.1
fsspec                    2026.3.0
h11                       0.16.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.11
ipykernel                 7.2.0
ipython                   9.12.0
ipython_pygments_lexers   1.1.1
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.6
joblib                    1.5.3
json5                     0.14.0
jsonpointer               3.1.1
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter_client            8.8.0
jupyter_core              5.9.1
jupyter-events            0.12.0
jupyter-lsp               2.3.1
jupyter_server            2.17.0
jupyter_server_terminals  0.5.4
jupyterlab                4.5.6
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
kaggle                    2.0.1
kagglehub                 1.0.0
kagglesdk                 0.1.18
kiwisolver                1.5.0
lark                      1.3.1
lightgbm                  4.6.0
MarkupSafe                3.0.3
matplotlib                3.10.8
matplotlib-inline         0.2.1
mediapipe                 0.10.33
mistune                   3.2.0
mpmath                    1.3.0
narwhals                  2.19.0
nbclient                  0.10.4
nbconvert                 7.17.0
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.6.1
nltk                      3.9.4
notebook                  7.5.5
notebook_shim             0.2.4
NRCLex                    3.0.0
numpy                     2.4.3
opencv-contrib-python     4.13.0.92
opencv-python             4.13.0.92
opencv-python-headless    4.13.0.92
openpyxl                  3.1.5
packaging                 26.0
pandas                    3.0.2
pandocfilters             1.5.1
parso                     0.8.6
pillow                    12.1.1
pip                       26.0.1
platformdirs              4.9.4
plotly                    6.7.0
polars                    1.39.3
polars-runtime-32         1.39.3
prometheus_client         0.24.1
prompt_toolkit            3.0.52
protobuf                  7.34.1
psutil                    7.2.2
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.19.2
pyparsing                 3.3.2
pypiwin32                 223
python-dateutil           2.9.0.post0
python-json-logger        4.1.0
python-slugify            8.0.4
pyttsx3                   2.99
pywin32                   311
pywinpty                  3.0.3
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
regex                     2026.5.9
requests                  2.33.1
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rpds-py                   0.30.0
scikit-learn              1.8.0
scipy                     1.17.1
seaborn                   0.13.2
Send2Trash                2.1.0
setuptools                81.0.0
six                       1.17.0
sounddevice               0.5.5
soupsieve                 2.8.3
stack-data                0.6.3
sympy                     1.14.0
terminado                 0.18.1
text-unidecode            1.3
textblob                  0.20.0
threadpoolctl             3.6.0
tinycss2                  1.4.0
torch                     2.11.0
torchvision               0.26.0
tornado                   6.5.5
tqdm                      4.67.3
traitlets                 5.14.3
typing_extensions         4.15.0
tzdata                    2025.3
ultralytics               8.4.38
ultralytics-thop          2.0.18
uri-template              1.3.0
urllib3                   2.6.3
vaderSentiment            3.3.2
wcwidth                   0.6.0
webcolors                 25.10.0
webencodings              0.5.1
websocket-client          1.9.0
wordcloud                 1.9.6
xgboost                   3.2.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

3.0.2
2.4.3

In [5]:
data1 = np.array([1,2,3,4,5])
print(data1)

[1 2 3 4 5]

In [6]:
data2 = np.array([[1, 2], [3, 4], [5, 6]])
df = pd.DataFrame(data2, columns=['A', 'B'])

df

   A  B
0  1  2
1  3  4
2  5  6

In [14]:
datasets = (
    data1,
    df
)

for data in datasets:
     print(data * 2)

[ 2  4  6  8 10]
    A   B
0   2   4
1   6   8
2  10  12

In [20]:
print(data1[0])
print("\n")
print(df['A'])

1


0    1
1    3
2    5
Name: A, dtype: int64

In [26]:
newdata = {
    "nama": ["Alice", "Bob", "Charlie"],
    "umur": [25, 30, 35],
    "jurusan": ["Informatika", "Sistem Informasi", "Teknik Komputer"],
    "angkatan": [2020, 2019, 2018]
}

df = pd.DataFrame(newdata)
print(df)
df

      nama  umur           jurusan  angkatan
0    Alice    25       Informatika      2020
1      Bob    30  Sistem Informasi      2019
2  Charlie    35   Teknik Komputer      2018

      nama  umur           jurusan  angkatan
0    Alice    25       Informatika      2020
1      Bob    30  Sistem Informasi      2019
2  Charlie    35   Teknik Komputer      2018

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nama      3 non-null      str
 1   umur      3 non-null      int64
 2   jurusan   3 non-null      str
 3   angkatan  3 non-null      int64
dtypes: int64(2), str(2)
memory usage: 228.0 bytes

In [28]:
df.describe()

       umur  angkatan
count   3.0       3.0
mean   30.0    2019.0
std     5.0       1.0
min    25.0    2018.0
25%    27.5    2018.5
50%    30.0    2019.0
75%    32.5    2019.5
max    35.0    2020.0